### ISSUE TITLE
Are you sticking to a specific version of nvim nightly for now?

### ISSUE THREAD

**Issue by partounian** [Allaman/nvim#20]
Been having some glitches, and was wondering if you're sticking to a mostly stable version of nvim that you could share.

**Comment by Allaman** [comment]
what kind of glitches? Since a week or so it is (again) fairly stable for me 
I am always running dev and upgrade almost each day so the answer is no 😄

**Comment by partounian** [comment]
Random segfault/crashes (twice a day?), but one issue I see very often is when I use `:e filepath/filename` I see the error

```
Error executing vim.schedule lua callback: ...m/site/pack/packer/start/nui.nvim/lua/nui/split/init.lua:147: Invalid window id: 1276
stack traceback:
        [C]: in function 'nvim_set_current_win'
        ...m/site/pack/packer/start/nui.nvim/lua/nui/split/init.lua:147: in function '_open_window'
        ...m/site/pack/packer/start/nui.nvim/lua/nui/split/init.lua:210: in function 'mount'
        .../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:825: in function 'create_window'
        .../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:947: in function 'draw'
        .../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1084: in function 'show_nodes'
        ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:103: in function 'job_complete'
        ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:125: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

I also have been seeing lag in general when typing in the command bar(?), or whatever is the proper name for the bar at the bottom. 

Sometimes see random cmdheight issues, but I guess https://github.com/neovim/neovim/pull/20249 will fix those.

**Comment by partounian** [comment]
Do you happen to know if it's possible to customize the gofmt/gopls rules? I tried searching but looks like they are strongly going for convention over configuration. Currently, some package names are using underscores or camelCase and was hoping I can disable that, until I'm able to notify rest of my team, change all these incorrect package names & folders.

Sorry for typing so much, but I hope this is better than creating multiple tickets.

**Comment by Allaman** [comment]
That's a lot of typing 😄 
- Random segfault/crashes (twice a day?) 
this was the case for me, too. I even wrote on [reddit](https://www.reddit.com/r/neovim/comments/ww6y1p/neovim_seg_faults_is_it_just_me/) with not much outcome. Since a couple of weeks I have no seg faults anymore. 

- when I use :e filepath/filename
I barely use `:e` for opening files... But as the error not always occurs maybe you can limit it to special circumstances?  A opened special buffer,...

- I also have been seeing lag in general when typing in the command bar(?), or whatever is the proper name for the bar at the bottom.
Also no issues but I have to admit that I went back to `cmdheight=1` because I experienced a lot of glitches and unwanted behaviour with `cmdheight=0`. Sadly

Regarding your go question:
I think that's the whole point. Everybody's code hast the same formatting and convention (which I do like). When you are aware of options how to customize gofmt/gopls I can have a deeper look on how to inject those to the LSP's call :)

If you are just talking about disabling the warnings in the LSP I am not aware how to only disable certain diagnostics. You could however toggle diagnostics on/off with <leader>md but you loose all diagnostic info in the buffer. (in the statusline they would still appear)

**Comment by partounian** [comment]
If anyone reads this for the underline / package name issue. I submitted a PR yesterday to allow you to configure go.nvim & disable it. https://github.com/ray-x/go.nvim/pull/221/files

**Comment by Allaman** [comment]
@partounian nice! I think I'll use this too :) https://github.com/Allaman/nvim/commit/a9717165237cfd9262f224eeef88e2aa22e39287
