### ISSUE TITLE
Replace all doesn't work

### ISSUE THREAD

**Issue by aleshkashell** [Allaman/nvim#73]
Get error when I'm trying to replace all using `<leader>RR`
```
E5108: Error executing lua: ...share/nvim/lazy/nvim-spectre/lua/spectre/state_utils.lua:13: attempt to index field 'user_config' (a nil value)
stack traceback:
	...share/nvim/lazy/nvim-spectre/lua/spectre/state_utils.lua:13: in function 'get_replace_creator'
	...cal/share/nvim/lazy/nvim-spectre/lua/spectre/actions.lua:153: in function 'run_replace'
	/home/aleshka/.config/nvim/lua/core/plugins/spectre.lua:47: in function </home/aleshka/.config/nvim/lua/core/plugins/spectre.lua:46>
```
I'm not sure if it's an issue in current setup or problem with spectre plugin itself.
It's reproducible in image allaman/nvim.

**Comment by Allaman** [comment]
Hello! 

Good catch and thank you for your feedback! I think this was not Spectre related. The user-config handling was missing a condition. In the Docker image, it was not created due to an error and I guess that you have not created it either.

The commit fixes the Docker image that now creates an empty user config file, although this is now not necessary anymore because in the same commit I implemented a check for the user-config file. If it does not exist, only the default config is loaded.

**Comment by aleshkashell** [comment]
Looks like fix didn't help. I applied it to my current installation and tried fresh one on another system - result is the same.
Also, config `.nvim_config.lua` is not created automatically if it's absent.

**Comment by Allaman** [comment]
hmm, this time, I cannot reproduce it. 

As I know that there might happen some strange things during the docker build, I followed a more manual check:
![spectre](https://github.com/Allaman/nvim/assets/12184268/36f205ce-5fd8-4675-ab61-47def65e7688)

1.  Start the base image of allaman/nvim `docker run -it --name nvim --entrypoint /bin/bash --rm allaman/nvim-full:latest`
2. Clone the config to .config/nvim `git clone https://github.com/Allaman/nvim.git .config/nvim`
3. Start nvim and push away the errors. These are normal at a fresh start because many packages are missing
4. Run `_Lazy` and hit `I` to install all packages
5. Wait until all parsers are finished.
6. Run `nvim test` and enter some text. Save it `:w` 
7. Start Spectre with `<leader>Rf` for instance and enter search/replace terms
8. Hit `<leader>RR>` 

> Also, config .nvim_config.lua is not created automatically if it's absent.
Yeah, intentionally, I would rather not mess around with the user's files. The former commit should have fixed the handling. Note that in the above steps, I did not create .nvim_config.lua either.

**Comment by aleshkashell** [comment]
> hmm, this time, I cannot reproduce it.
>  .........

Thank you, it's my misunderstanding how it should work.
If I do
> Start Spectre with <leader>Rf for instance and enter search/replace terms
> Hit <leader>RR

it works.
But if I start new instances of nvim, then Hit `<leader>RR` I get error about 'user_config'. If after that I repeat `<leader>Rf` with `<leader>RR` the latter operation doesn't work with message `it is already running`

**Comment by Allaman** [comment]
I should invest how to only show the "replace" commands when in an actual Spectre buffer. I'll admit that it can be misleading, especially without reading the Spectre Readme.

Le'ts keep this issue open so that I don't forget it 😆

**Comment by Allaman** [comment]
@aleshkashell now the "replace" mappings are only shown in a spectre buffer. I hope this will prevent any confusion. :)
