### ISSUE TITLE
How to enable language server for yaml?

### ISSUE THREAD

**Issue by aphsa** [Allaman/nvim#74]
I get the following output even after installing ansible-language-server via mason. ansible-language-server is in my shell path.

```
Spawning language server with cmd: `table: 0x40149d60` failed. The language server is either not installed, missing from PATH, or not executable.
Spawning language server with cmd: `table: 0x40149d60` failed. The language server is either not installed, missing from PATH, or not executable.
```
How to ensure ansible-language-server is enabled by default when opening yaml files?
Ubuntu 22.04 user here.

**Comment by Allaman** [comment]
Hello, 
is the output of `:lua vim.fn.executable('ansible-language-server')` `1` ? If it is not 1, then Neovim really can't find the executable, and you should double-check your PATH.

I don't work with Ansible that much anymore, but I looked into how I would set it up. You should take a look at https://github.com/mfussenegger/nvim-ansible/blob/main/ftdetect/ansible.vim. This plugin handles the filetype detection because by default, ansiblels looks for [yaml.ansible](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#ansiblels) filetype. 

However, if I do run `set filetype=yaml.ansible` the LSP gets spawned automatically. 
<img width="837" alt="image" src="https://github.com/Allaman/nvim/assets/12184268/e79ec72b-8a4a-4864-9026-0cfe0df57f02">

Also note that the name of the LSP for nvim-lspconfig is `ansiblels` and not `ansible-language-server`
<img width="264" alt="image" src="https://github.com/Allaman/nvim/assets/12184268/273b2f26-f830-472c-b380-35dd3c35c403">

**Comment by aphsa** [comment]
After adding ansiblels to the list of lsp_servers set filetype=yaml.ansible all of this works fine.

**Comment by aphsa** [comment]
After working on the file I get this dark blue boxes which stays and hides my code I until I quit neovim. What is the issue?

![Untitled](https://github.com/Allaman/nvim/assets/26134018/4a278543-a9b0-4886-a21e-451aad98082b)

**Comment by Allaman** [comment]
Sry, I have no clue why this happens. This might be an issue with your terminal. Or an issue of Neovim not correctly redrawing (did you run `:e` to reopen the file or `:redraw!`?). This is nasty shit :/
